#!/bin/bash
#SBATCH -A uot189
#SBATCH --job-name="graph.local"
#SBATCH --output="graph.local.out"
#SBATCH --partition=compute
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --mem=16G
#SBATCH --export=ALL 
#SBATCH --time=20

module load cpu/0.15.4 gcc/7.5.0 openjdk hadoop/3.2.2
SW=/expanse/lustre/projects/uot189/fegaras

export TMPDIR=$HOME/tmp

rm -rf intermediate output
hadoop --config $SW/conf jar graph.jar Graph small-graph.csv intermediate output
cp output/part* small-output.txt
